# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a5ebd34d178d45fe79191074ed9db96b120b7dbece07b02c59b15e04d326bd3918dde394bce0c46cfaae5dfe79616a0bd9bb5c58365a281f6b7006a8c5ff81a

test:
  secret_key_base: b197f885457db3961bed6e191ef50c42dc98aad1c66671dadfcbe544f0d96273496625e5c3c7e21ed6193aec718a2efcd3e2f9ff75b6ff2796ec44b8a165a33d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
